[archives]
git-tree-sha1 = "0adbb9c91922f1e2cc78aa2628ac014495e24773"

    [[archives.download]]
    url = "https://github.com/Liozou/CrystalNetsArchive/releases/download/V2.5/archives.tar.xz"
    sha256 = "cbaba5921b3b0d12a580446a9c62876f7dd86b6beb1bfb55ebd806a97621b8a7"

    [[archives.download]]
    url = "https://github.com/Liozou/CrystalNetsArchive/releases/download/V2.5/archives.zip"
    sha256 = "06b6571c66c13fbcc28d72dfd81dbe1722d7250b1121180594e5020d45b4143d"
